[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/kickstart.nvim"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
