[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/Bejdenn/kickstart.nvim"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
[".bash/themes/aphrodite-terminal-theme"]
    type = "git-repo"
    url = "git@github.com:Bejdenn/aphrodite-terminal-theme.git"
    refreshPeriod = "168h"
