[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:Bejdenn/nvim.git"
    refreshPeriod = "168h"

# Bootstraps Obsidian plugins by downloading the latest
# release of the plugin and include them in the vault
#
# There is no refreshPeriod defined because I let Obsidian
# handle the plugins after the bootstraping
{{ $plugins := dict
  "kepano"        "obsidian-hider"
  "remotely-save" "remotely-save"
  "blacksmithgu"  "obsidian-dataview" -}}

{{ range $owner, $repo := $plugins -}}
{{ range $file := list "manifest.json" "main.js" "styles.css" -}}
[{{ printf "\"Obsidian/.obsidian/plugins/%s/%s\"" $repo $file }}]
    type = "file"
    url = {{ printf "\"https://github.com/%s/%s/releases/latest/download/%s\"" $owner $repo $file }}
{{ end -}}
{{ end -}}
