#!/usr/bin/env bash

yayf() {
	if [ "$1" == "-S" ] || [ "$1" == "--sync" ]; then
		yay -Slq | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S
		gum spin --title "Done!" -- sleep 2
	elif [ "$1" == "-R" ] || [ "$1" == "--remove" ]; then
		yay -Qqe | fzf --multi --preview 'yay -Qi {1}' --preview-window=down:75% | xargs -ro yay -Rns
		gum spin --title "Done!" -- sleep 2
	else
		echo "usage:
	yayf <operation>
operations:
	yayf {-S --sync}
	yayf {-R --remove}
"
	fi
}

gemini() {
	export GEMINI_API_KEY="op://Private/Gemini API Key/credential"
	op run --no-masking -- gemini
}
