import = [
    "~/.config/alacritty/theme.toml"
]

[shell]
program = "/usr/bin/sh"
args = ["/home/dennisbejze/.config/alacritty/tmux.sh"]

[font]
size = 11 
# size = 14 # on high resolutions
normal = { family = "Iosevka Term", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }

[window]
padding.x = 16
padding.y = 14

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"
