import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[font]
size = 12.0
normal = { family = "IosevkaTerm", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"
