#!/bin/bash

function dispatch() {
  hyprctl --batch "$1" >/dev/null
  restart-app waybar
}

function enable_single_monitor() {
  declare cmd
  for item in $(hyprctl monitors all -j | jq -r ".[] | .name | select(. != \"$1\")"); do
    cmd="$cmd; keyword monitor $item, disable"
  done

  dispatch "$cmd"
}

declare -A modes
modes=(["mirror"]="Mirror" ["reset"]="Reset" ["builtin"]="Built-in only" ["external"]="External only")

declare -A icons
icons=(["mirror"]="" ["reset"]="󰓦" ["builtin"]="󱧐" ["external"]="󱒃")

echo -e "\0no-custom\x1ftrue"
# Use markup
echo -e "\0markup-rows\x1ftrue"
echo -e "\0prompt\x1fDisplay mode"

if [ -n "$1" ]; then
  case "$1" in
  *mirror*)
    hyprctl reload >/dev/null

    declare cmd
    for item in $(hyprctl monitors all -j | jq -r '.[] | .name | select(. != "eDP-1")'); do
      cmd="$cmd; keyword monitor $item, preferred, auto, 1, mirror, eDP-1"
    done

    dispatch "$cmd"
    ;;

  *reset*)
    for item in $(hyprctl monitors all -j | jq -r ".[] | .name"); do
      cmd="$cmd; keyword monitor $item, disable"
    done

    dispatch "$cmd"
    hyprctl reload >/dev/null
    ;;
  *builtin*)
    hyprctl reload >/dev/null
    enable_single_monitor "eDP-1"
    ;;
  *external*)
    hyprctl reload >/dev/null

    for item in $(hyprctl monitors all -j | jq -r '.[] | .name | select(. != "eDP-1")'); do
      enable_single_monitor "$item"
    done
    ;;
  *)
    notify-send "Unsupported display mode: $1"
    ;;
  esac
else
  for m in "${!modes[@]}"; do
    echo -e "$m\0display\x1f<span>${icons[$m]}</span> ${modes[$m]}"
  done
fi
