# Floating windows
windowrule = tag +floating-window, match:class (blueberry.py|Wiremix|org.gnome.NautilusPreviewer)
windowrule = match:tag floating-window, float on, center on, size = 800 600
windowrule = match:class ^(mpv|com.github.PintaProject.Pinta|org.gnome.NautilusPreviewer)$, opacity 1 1
